name: http_logger
description: A simple command-line application to log http traffic using dart
version: 1.0.0
environment:
  sdk: '>=2.14.4 <3.0.0'

dev_dependencies:
  lints: ^1.0.1

dependencies:
  intl: ^0.19.0
  shelf: ^1.4.1
